function fadePlayer(player){$("#dealoutcard"+(2*player-1)).fadeTo(1000,0.3);$("#dealoutcard"+(2*player)).fadeTo(1000,0.3);}
function fadeBackPlayer(player){$("#dealoutcard"+(2*player-1)).fadeTo(1000,1);$("#dealoutcard"+(2*player)).fadeTo(1000,1);}
function showPlayers(amount){for(i=1;i<amount+1;i++){$("#player"+i).fadeTo(1000,1);}}
function changePlayerBet(playerNum,newBet){$("#playerbet"+playerNum).html(newBet+" ");}
function changePlayerName(playerNum,newName){$("div#player"+playerNum+"> div.playername").html(newName);}
function resetMoney(){$(".playersum").html("0 €");$("#pot").html("0");}
function setPot(sum){$("#pot").html(sum+" €");}
function setPlayerMoney(playerNum,sum){$("div#player"+playerNum
+"> div.playerdata > div.playerdetail > div.playersum").html(sum+" €");}
function addTextToHistory(text){$("#stats").append("Server> "+text+"\n---\n");var elem=document.getElementById('stats');elem.scrollTop=elem.scrollHeight;}
function addTextToChat(name,text){$("#chatoutput").append(name+"> "+text+"\n");var elem=document.getElementById('chatoutput');elem.scrollTop=elem.scrollHeight;}
function dealCardsToPlayer1(n){$(document).ready(function(){$("#dealoutcard1").delay(n).animate({opacity:"1",left:"-=432",top:"+=171",height:"-=28",width:"-=21"},1000);$("#dealoutcard2").delay(n+300).animate({opacity:"1",left:"-=403",top:"+=180",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer1(n){$(document).ready(function(){$("#dealoutcard1").delay(n).animate({opacity:"1",left:"+=432",top:"-=171",height:"+=28",width:"+=21"},1000);$("#dealoutcard2").delay(n+300).animate({opacity:"1",left:"+=403",top:"-=180",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer2(n){$(document).ready(function(){$("#dealoutcard3").delay(n).animate({opacity:"1",left:"-=504",top:"-=30",height:"-=28",width:"-=21"},1000);$("#dealoutcard4").delay(n+300).animate({opacity:"1",left:"-=475",top:"-=21",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer2(n){$(document).ready(function(){$("#dealoutcard3").delay(n).animate({opacity:"1",left:"+=504",top:"+=30",height:"+=28",width:"+=21"},1000);$("#dealoutcard4").delay(n+300).animate({opacity:"1",left:"+=475",top:"+=21",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer3(n){$(document).ready(function(){$("#dealoutcard5").delay(n).animate({opacity:"1",left:"-=433",top:"-=231",height:"-=28",width:"-=21"},1000);$("#dealoutcard6").delay(n+300).animate({opacity:"1",left:"-=403",top:"-=220",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer3(n){$(document).ready(function(){$("#dealoutcard5").delay(n).animate({opacity:"1",left:"+=433",top:"+=231",height:"+=28",width:"+=21"},1000);$("#dealoutcard6").delay(n+300).animate({opacity:"1",left:"+=403",top:"+=220",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer4(n){$(document).ready(function(){$("#dealoutcard7").delay(n).animate({opacity:"1",left:"-=233",top:"-=262",height:"-=28",width:"-=21"},1000);$("#dealoutcard8").delay(n+300).animate({opacity:"1",left:"-=202",top:"-=250",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer4(n){$(document).ready(function(){$("#dealoutcard7").delay(n).animate({opacity:"1",left:"+=233",top:"+=262",height:"+=28",width:"+=21"},1000);$("#dealoutcard8").delay(n+300).animate({opacity:"1",left:"+=202",top:"+=250",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer5(n){$(document).ready(function(){$("#dealoutcard9").delay(n).animate({opacity:"1",left:"-=32",top:"-=262",height:"-=28",width:"-=21"},1000);$("#dealoutcard10").delay(n+300).animate({opacity:"1",left:"-=3",top:"-=250",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer5(n){$(document).ready(function(){$("#dealoutcard9").delay(n).animate({opacity:"1",left:"+=32",top:"+=262",height:"+=28",width:"+=21"},1000);$("#dealoutcard10").delay(n+300).animate({opacity:"1",left:"+=3",top:"+=250",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer6(n){$(document).ready(function(){$("#dealoutcard11").delay(n).animate({opacity:"1",left:"+=148",top:"-=230",height:"-=28",width:"-=21"},1000);$("#dealoutcard12").delay(n+300).animate({opacity:"1",left:"+=178",top:"-=220",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer6(n){$(document).ready(function(){$("#dealoutcard11").delay(n).animate({opacity:"1",left:"-=148",top:"+=230",height:"+=28",width:"+=21"},1000);$("#dealoutcard12").delay(n+300).animate({opacity:"1",left:"-=178",top:"+=220",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer7(n){$(document).ready(function(){$("#dealoutcard13").delay(n).animate({opacity:"1",left:"+=210",top:"-=30",height:"-=28",width:"-=21"},1000);$("#dealoutcard14").delay(n+300).animate({opacity:"1",left:"+=239",top:"-=21",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer7(n){$(document).ready(function(){$("#dealoutcard13").delay(n).animate({opacity:"1",left:"-=210",top:"+=30",height:"+=28",width:"+=21"},1000);$("#dealoutcard14").delay(n+300).animate({opacity:"1",left:"-=239",top:"+=21",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer8(n){$(document).ready(function(){$("#dealoutcard15").delay(n).animate({opacity:"1",left:"+=148",top:"+=171",height:"-=28",width:"-=21"},1000);$("#dealoutcard16").delay(n+300).animate({opacity:"1",left:"+=178",top:"+=180",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer8(n){$(document).ready(function(){$("#dealoutcard15").delay(n).animate({opacity:"1",left:"-=148",top:"-=171",height:"+=28",width:"+=21"},1000);$("#dealoutcard16").delay(n+300).animate({opacity:"1",left:"-=178",top:"-=180",height:"+=28",width:"+=21"},1000);});}
function dealCardsToPlayer9(n){$(document).ready(function(){$("#dealoutcard17").delay(n).animate({opacity:"1",left:"-=52",top:"+=221",height:"-=28",width:"-=21"},1000);$("#dealoutcard18").delay(n+300).animate({opacity:"1",left:"-=22",top:"+=230",height:"-=28",width:"-=21"},1000);});}
function unDealCardsToPlayer9(n){$(document).ready(function(){$("#dealoutcard17").delay(n).animate({opacity:"1",left:"+=52",top:"-=221",height:"+=28",width:"+=21"},1000);$("#dealoutcard18").delay(n+300).animate({opacity:"1",left:"+=22",top:"-=230",height:"+=28",width:"+=21"},1000);});}
function dealCards(n){switch(n){case 1:dealCardsToPlayer1(300);break;case 2:dealCardsToPlayer1(300);dealCardsToPlayer2(600);break;case 3:dealCardsToPlayer1(300);dealCardsToPlayer2(600);dealCardsToPlayer3(800);break;case 4:dealCardsToPlayer1(300);dealCardsToPlayer2(600);dealCardsToPlayer3(800);dealCardsToPlayer4(1200);break;case 5:dealCardsToPlayer1(300);dealCardsToPlayer2(600);dealCardsToPlayer3(800);dealCardsToPlayer4(1200);dealCardsToPlayer5(1500);break;case 6:dealCardsToPlayer1(300);dealCardsToPlayer2(600);dealCardsToPlayer3(800);dealCardsToPlayer4(1200);dealCardsToPlayer5(1500);dealCardsToPlayer6(1800);break;case 7:dealCardsToPlayer1(300);dealCardsToPlayer2(600);dealCardsToPlayer3(800);dealCardsToPlayer4(1200);dealCardsToPlayer5(1500);dealCardsToPlayer6(1800);dealCardsToPlayer7(2100);break;case 8:dealCardsToPlayer1(300);dealCardsToPlayer2(600);dealCardsToPlayer3(800);dealCardsToPlayer4(1200);dealCardsToPlayer5(1500);dealCardsToPlayer6(1800);dealCardsToPlayer7(2100);dealCardsToPlayer8(2400);break;case 9:dealCardsToPlayer1(300);dealCardsToPlayer2(600);dealCardsToPlayer3(800);dealCardsToPlayer4(1200);dealCardsToPlayer5(1500);dealCardsToPlayer6(1800);dealCardsToPlayer7(2100);dealCardsToPlayer8(2400);dealCardsToPlayer9(2700);break;}}
function unDealCards(n){switch(n){case 1:unDealCardsToPlayer1(300);break;case 2:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);break;case 3:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);unDealCardsToPlayer3(900);break;case 4:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);unDealCardsToPlayer3(900);unDealCardsToPlayer4(1200);break;case 5:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);unDealCardsToPlayer3(900);unDealCardsToPlayer4(1200);unDealCardsToPlayer5(1500);break;case 6:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);unDealCardsToPlayer3(900);unDealCardsToPlayer4(1200);unDealCardsToPlayer5(1500);unDealCardsToPlayer6(1800);break;case 7:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);unDealCardsToPlayer3(900);unDealCardsToPlayer4(1200);unDealCardsToPlayer5(1500);unDealCardsToPlayer6(1800);unDealCardsToPlayer7(2100);break;case 8:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);unDealCardsToPlayer3(900);unDealCardsToPlayer4(1200);unDealCardsToPlayer5(1500);unDealCardsToPlayer6(1800);unDealCardsToPlayer7(2100);unDealCardsToPlayer8(2400);break;case 9:unDealCardsToPlayer1(300);unDealCardsToPlayer2(600);unDealCardsToPlayer3(900);unDealCardsToPlayer4(1200);unDealCardsToPlayer5(1500);unDealCardsToPlayer6(1800);unDealCardsToPlayer7(2100);unDealCardsToPlayer8(2400);unDealCardsToPlayer9(2700);break;}}
function dealTableCards(n){$(document).ready(function(){$("#dealoutcard19").delay(n).animate({left:"-=300"},1000);$("#dealoutcard20").delay(n+300).animate({left:"-=225"},1000);$("#dealoutcard21").delay(n+600).animate({left:"-=150"},1000);$("#dealoutcard22").delay(n+900).animate({left:"-=75"},1000);});}
function unDealTableCards(n){$(document).ready(function(){$("#dealoutcard19").delay(n).animate({left:"+=300"},1000);$("#dealoutcard20").delay(n+300).animate({left:"+=225"},1000);$("#dealoutcard21").delay(n+600).animate({left:"+=150"},1000);$("#dealoutcard22").delay(n+900).animate({left:"+=75"},1000);});}
function showAnnouncement(duration,textsize,text){$(document).ready(function(){$("#announcement").css("font-size",textsize+"px");$("#announcement").html(text);$("#announcement").delay(duration).fadeTo(800,0,function(){$("#announcement").html("");});$("#announcement").fadeTo(0,100);});}
function changeDisplay(player,choice){$(document).ready(function(){$("#player"+player).children(".playerdata").children(".playerdisplay").children(".playerdisplayimage").fadeTo(500,0.0,function(){$("#player"+player).children(".playerdata").children(".playerdisplay").children(".playerdisplayimage").attr("src","images/display"
+choice
+".png");});$("#player"+player).children(".playerdata").children(".playerdisplay").children(".playerdisplayimage").fadeTo(3000,100.0);});}
function hidePlayer(player){$(document).ready(function(){$("#player"+player).fadeOut(600);});setTimeout("removePlayer(player)",900);}
function removePlayer(player){$(document).ready(function(){$("#player"+player).remove();});}
function hidePlayerButtons(i){if(i){$("#ourbuttons").hide('slow',function(){});}
if(!i){$("#ourbuttons").show(600);}}
function hidePlayers(number){for(i=0;i<number;i++){hidePlayer(9-i);}}
function flipCards(player,card1,card2){$("#dealoutcard"+(2*player-1)).attr("src","images/cards/"+card1+".png");$("#dealoutcard"+(2*player)).attr("src","images/cards/"+card2+".png");}
function flipFlop(card1,card2,card3){$(document).ready(function(){$("#dealoutcard19").attr("src","images/cards/"+card1+".png");$("#dealoutcard20").attr("src","images/cards/"+card2+".png");$("#dealoutcard21").attr("src","images/cards/"+card3+".png");});}
function flipTurn(card){$(document).ready(function(){$("#dealoutcard22").attr("src","images/cards/"+card+".png");});}
function flipRiver(card){$(document).ready(function(){$("#dealoutcard23").attr("src","images/cards/"+card+".png");});}
function cardsBackside(){$(document).ready(function(){for(i=1;i<24;i++){$("#dealoutcard"+i).attr("src","images/cardBackSide.png");}});}
function clearDealer(){$(document).ready(function(){for(i=1;i<=9;i++){$("#player"+i).children(".playerdata").children(".playerdetail").children(".playerstatus").children(".playerstatusimage").hide();}});}
function setDealer(player){clearDealer();$(document).ready(function(){$("#player"+player).children(".playerdata").children(".playerdetail").children(".playerstatus").children(".playerstatusimage").show();});}
var playerAmount=0;function initDisplay(){}
function updatePlayers(players){showPlayers(9);hidePlayers(9-players.length);for(i=0;i<players.length;i++){changePlayerName(i+1,players[i]);}}
function getCardMapping(card){var valuehash={0:'Ace',1:'Two',2:'Three',3:'Four',4:'Five',5:'Six',6:'Seven',7:'Eight',8:'Nine',9:'Ten',10:'Jack',11:'Queen',12:'King'};var suithash={0:'diamonds',1:'spades',2:'hearts',3:'clubs'};var splittedCard=card.split("-");return suithash[Number(splittedCard[1])]+valuehash[Number(splittedCard[0])];}
function updateRiver(cards){var mappedCards=new Array();for(i=0;i<cards.length;i++){mappedCards.push(getCardMapping(cards[i]));}
flipRiver(mappedCards[0]);}
function updateChat(name,message){addTextToChat(name,message);}
function updatePot(amount){setPot(amount);}
function updateWinner(name){showAnnouncement(6000,26,name);setTimeout('unDealCards('+playerAmount+')',1400);unDealTableCards(0);setTimeout('cardsBackside()',800);}
function updateResetStatus(){for(i=0;i<playerAmount;i++){changeDisplay(i+1,"Idle");}}
function updateRound(round){showAnnouncement(4000,26,round);}
function updateCards(id,cards){var mappedCards=new Array();for(i=0;i<cards.length;i++){mappedCards.push(getCardMapping(cards[i]));}
flipCards(Number(id)+1,mappedCards[0],mappedCards[1]);}
function updateDealer(id){setDealer(Number(id)+1);}
function updateBet(id,amount){changePlayerBet(Number(id)+1,amount);}
function updateStatus(id,status){if(status=="Fold")
fadePlayer(Number(id)+1);changeDisplay(Number(id)+1,status);}
function updateMessage(message){addTextToHistory(message);}
function updateFlop(cards){dealTableCards(0);var mappedCards=new Array();for(i=0;i<cards.length;i++){mappedCards.push(getCardMapping(cards[i]));}
flipFlop(mappedCards[0],mappedCards[1],mappedCards[2]);}
function updateTurn(cards){var mappedCards=new Array();for(i=0;i<cards.length;i++){mappedCards.push(getCardMapping(cards[i]));}
flipTurn(mappedCards[0]);}
function processData(data){var parsedData=jsonParse(data);var infoType=parsedData.type;var infoData=String(parsedData.data);var infoName=parsedData.name;var infoId=String(parsedData.id);if(infoType=="players"){var playerData=infoData.split(",");var players=new Array();for(i=0;i<playerData.length;i++){players.push(playerData[i]);}
playerAmount=players.length;updatePlayers(players);}else if(infoType=="round"){updateRound(infoData);}else if(infoType=="playercards"){var playerCards=infoData.split(",");var cards=new Array();for(i=0;i<playerCards.length;i++){cards.push(playerCards[i]);}
updateCards(infoId,cards);setTimeout('dealCards('+playerAmount+')',1400);}else if(infoType=="dealer"){updateDealer(infoId);}else if(infoType=="bet"){updateBet(infoId,infoData);}else if(infoType=="status"){updateStatus(infoId,infoName);}else if(infoType=="resetstatus"){updateResetStatus();}else if(infoType=="message"){updateMessage(infoData);}else if(infoType=="flop"){var tableCards=infoData.split(",");var cards=new Array();for(i=0;i<tableCards.length;i++){cards.push(tableCards[i]);}
updateFlop(cards);}else if(infoType=="turn"){var tableCards=infoData.split(",");var cards=new Array();for(i=0;i<tableCards.length;i++){cards.push(tableCards[i]);}
updateTurn(cards);}else if(infoType=="river"){var tableCards=infoData.split(",");var cards=new Array();for(i=0;i<tableCards.length;i++){cards.push(tableCards[i]);}
updateRiver(cards);}else if(infoType=="chat"){updateChat(infoName,infoData);}else if(infoType=="pot"){updatePot(infoData);}else if(infoType=="showdown"){updateWinner(infoName);}else if(infoType=="otherscards"){var playerCards=infoData.split(",");var cards=new Array();for(i=0;i<playerCards.length;i++){cards.push(playerCards[i]);}
updateCards(infoId,cards);}}
function getNewInfoAndUpdateUI(){$.ajax({type:"GET",url:"server",data:"task=getinfo",cache:false,success:function(result){processData(result);getNewInfoAndUpdateUI();}});}
function startUpdater(){getNewInfoAndUpdateUI();}
function spectate(){$.ajax({type:"POST",url:"server",data:"task=spec",cache:false,success:function(result){}});}
function initGame(){initDisplay();startUpdater();spectate();}
function joinGame(){var name=prompt("What is your name","name");$.ajax({type:"POST",url:"server",data:"task=join&name="+name,cache:false,success:function(result){}});}
function chat(){var message=$("#usermsg").val();$.ajax({url:"server",data:"task=chat&message="+message,cache:false,success:function(result){$("#usermsg").val("");}});}
$(document).ready(function(){$("#newgamebutton").click(function(){joinGame();});$("#exitbutton").click(function(){$.ajax({type:"POST",url:"server",data:"task=starthand",cache:false,success:function(result){}});});$("#buttonfold").click(function(){$.ajax({type:"POST",url:"server",data:"task=fold",cache:false,success:function(result){}});});$("#buttoncall").click(function(){$.ajax({type:"POST",url:"server",data:"task=call",cache:false,success:function(result){}});});$("#buttonraise").click(function(){$.ajax({type:"POST",url:"server",data:"task=raise",cache:false,success:function(result){}});});$("#usermsg").keypress(function(event){if(event.which=="13"){$("#submitmsg").click();}});$("#submitmsg").click(function(){chat();});});var jsonParse=(function(){var number='(?:-?\\b(?:0|[1-9][0-9]*)(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?\\b)';var oneChar='(?:[^\\0-\\x08\\x0a-\\x1f\"\\\\]'
+'|\\\\(?:[\"/\\\\bfnrt]|u[0-9A-Fa-f]{4}))';var string='(?:\"'+oneChar+'*\")';var jsonToken=new RegExp('(?:false|true|null|[\\{\\}\\[\\]]'
+'|'+number
+'|'+string
+')','g');var escapeSequence=new RegExp('\\\\(?:([^u])|u(.{4}))','g');var escapes={'"':'"','/':'/','\\':'\\','b':'\b','f':'\f','n':'\n','r':'\r','t':'\t'};function unescapeOne(_,ch,hex){return ch?escapes[ch]:String.fromCharCode(parseInt(hex,16));}
var EMPTY_STRING=new String('');var SLASH='\\';var firstTokenCtors={'{':Object,'[':Array};var hop=Object.hasOwnProperty;return function(json,opt_reviver){var toks=json.match(jsonToken);var result;var tok=toks[0];var topLevelPrimitive=false;if('{'===tok){result={};}else if('['===tok){result=[];}else{result=[];topLevelPrimitive=true;}
var key;var stack=[result];for(i=1-topLevelPrimitive,n=toks.length;i<n;++i){tok=toks[i];var cont;switch(tok.charCodeAt(0)){case 0x22:tok=tok.substring(1,tok.length-1);if(tok.indexOf(SLASH)!==-1){tok=tok.replace(escapeSequence,unescapeOne);}
cont=stack[0];if(!key){if(cont instanceof Array){key=cont.length;}else{key=tok||EMPTY_STRING;break;}}
cont[key]=tok;key=void 0;break;case 0x5b:cont=stack[0];stack.unshift(cont[key||cont.length]=[]);key=void 0;break;case 0x5d:stack.shift();break;case 0x66:cont=stack[0];cont[key||cont.length]=false;key=void 0;break;case 0x6e:cont=stack[0];cont[key||cont.length]=null;key=void 0;break;case 0x74:cont=stack[0];cont[key||cont.length]=true;key=void 0;break;case 0x7b:cont=stack[0];stack.unshift(cont[key||cont.length]={});key=void 0;break;case 0x7d:stack.shift();break;default:cont=stack[0];cont[key||cont.length]=+(tok);key=void 0;break;}}
if(topLevelPrimitive){if(stack.length!==1){throw new Error();}
result=result[0];}else{if(stack.length){throw new Error();}}
if(opt_reviver){var walk=function(holder,key){var value=holder[key];if(value&&typeof value==='object'){var toDelete=null;for(var k in value){if(hop.call(value,k)&&value!==holder){var v=walk(value,k);if(v!==void 0){value[k]=v;}else{if(!toDelete){toDelete=[];}
toDelete.push(k);}}}
if(toDelete){for(i=toDelete.length;--i>=0;){delete value[toDelete[i]];}}}
return opt_reviver.call(holder,key,value);};result=walk({'':result},'');}
return result;};})();function draw(){var canvas=document.getElementById("pokerTable");var raam=canvas.getContext("2d");raam.fillStyle="#61380B";raam.beginPath();raam.moveTo(160,0);raam.lineTo(440,0);raam.bezierCurveTo(650,0,650,300,440,300);raam.lineTo(160,300);raam.bezierCurveTo(-50,300,-50,0,160,0);raam.closePath();raam.fill();var raami_efekt=canvas.getContext("2d");raami_efekt.beginPath();raami_efekt.moveTo(160,0);raami_efekt.lineTo(440,0);raami_efekt.bezierCurveTo(650,0,650,300,440,300);raami_efekt.lineTo(160,300);raami_efekt.bezierCurveTo(-50,300,-50,0,160,0);raami_efekt.closePath();raami_efekt.lineWidth=1;var grdRaam1=raami_efekt.createLinearGradient(300,0,300,300);grdRaam1.addColorStop(0,"#3B240B");grdRaam1.addColorStop(1,"#000000");raami_efekt.strokeStyle=grdRaam1;raami_efekt.stroke();var raami_efekt2=canvas.getContext("2d");raami_efekt2.beginPath();raami_efekt2.moveTo(160,5);raami_efekt2.lineTo(440,5);raami_efekt2.bezierCurveTo(642,5,642,295,440,295);raami_efekt2.lineTo(160,295);raami_efekt2.bezierCurveTo(-42,295,-42,5,160,5);raami_efekt2.closePath();raami_efekt2.lineWidth=1;var grdRaam2=raami_efekt2.createLinearGradient(300,0,300,300);grdRaam2.addColorStop(0,"#000000");grdRaam2.addColorStop(1,"#FFFFFF");raami_efekt2.strokeStyle=grdRaam2;raami_efekt2.stroke();var laud=canvas.getContext("2d");var grd=laud.createLinearGradient(300,300,300,0);grd.addColorStop(0,"#0A2A0A");grd.addColorStop(1,"#0B610B");laud.fillStyle=grd;laud.beginPath();laud.moveTo(160,5);laud.lineTo(440,5);laud.bezierCurveTo(642,5,642,295,440,295);laud.lineTo(160,295);laud.bezierCurveTo(-42,295,-42,5,160,5);laud.closePath();laud.fill();var joon=canvas.getContext("2d");joon.beginPath();joon.moveTo(160,70);joon.lineTo(440,70);joon.bezierCurveTo(550,70,550,230,440,230);joon.lineTo(160,230);joon.bezierCurveTo(50,230,50,70,160,70);joon.closePath();joon.lineWidth=5;joon.strokeStyle="rgba(255,255,255,0.2)";joon.stroke();}